import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nike App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <span className={styles.textBackground}>Nike</span>
        <Slider />
      </main>
    </div>
  );
}
